INSERT INTO negocio (nombre, direccion, telefono, celular, social_media, photo_header_url, rating, website, map_location, descripcion)
VALUES
    ('The Mane Attraction',
     '{"calle":"Avenida de la Belleza","numero":"101","colonia":"Centro Histórico","cp":"06500","municipio":"Ciudad Glamour","localidad":"Distrito de Moda"}',
     '555-1234',
     '555-5678',
     '{"instagram":"https://www.instagram.com/themaneattraction", "facebook":"https://www.facebook.com/themaneattraction"}',
     'https://example.com/images/themaneattraction.jpg',
     4.7,
     'https://themaneattraction.com',
     '19.4326,-99.1332',
     'Este salón de belleza es conocido por sus servicios de peluquería de alta calidad. Especializado en cortes modernos, coloraciones y tratamientos capilares que hacen que tu melena sea el centro de todas las miradas.'),

    ('Nailed It! Studio',
     '{"calle":"Calle Esmalte","numero":"456","colonia":"La Bella Vista","cp":"06700","municipio":"Ciudad Arte","localidad":"Distrito de Uñas"}',
     '555-2345',
     '555-6789',
     '{"instagram":"https://www.instagram.com/naileditstudio"}',
     'https://example.com/images/naileditstudio.jpg',
     4.3,
     'https://naileditstudio.com',
     '20.1234,-98.7654',
     'Un espacio dedicado al arte de las uñas. Ofrece una amplia gama de servicios que incluyen manicuras, pedicuras, nail art y tratamientos de spa para manos y pies.'),

    ('Browtiful',
     '{"calle":"Boulevard de las Cejas","numero":"789","colonia":"Arcoíris","cp":"06800","municipio":"Ciudad Cejas","localidad":"Distrito de Belleza"}',
     '555-3456',
     '555-7890',
     '{"facebook":"https://www.facebook.com/browtiful"}',
     'https://example.com/images/browtiful.jpg',
     4.5,
     'https://browtiful.com',
     '21.5678,-97.6543',
     'El lugar perfecto para realzar tus cejas con estilos personalizados y servicios de microblading. Su enfoque está en transformar tus cejas para enmarcar tu rostro de manera perfecta.'),

    ('Lash & Dash',
     '{"calle":"Avenida de las Pestañas","numero":"101","colonia":"Vista Hermosa","cp":"06900","municipio":"Ciudad Ojos","localidad":"Distrito de Pestañas"}',
     '555-4567',
     '555-8901',
     '{"youtube":"https://www.youtube.com/channel/lashdash"}',
     'https://example.com/images/lashdash.jpg',
     4.8,
     'https://lashdash.com',
     '22.6789,-96.5432',
     'Este estudio ofrece servicios rápidos y profesionales para realzar tus pestañas, incluyendo extensiones y levantamientos que te dejarán lista para cualquier ocasión en poco tiempo.'),

    ('Glow & Flow Salon',
     '{"calle":"Carretera del Sol","numero":"202","colonia":"Luz de Luna","cp":"07000","municipio":"Ciudad Brillo","localidad":"Distrito de Resplandor"}',
     '555-5678',
     '555-9012',
     '{"tiktok":"https://www.tiktok.com/@glowflowsalon"}',
     'https://example.com/images/glowflowsalon.jpg',
     4.9,
     'https://glowflowsalon.com',
     '23.7890,-95.4321',
     'Una experiencia integral de belleza que combina servicios para cabello, uñas, cejas y pestañas. Su ambiente relajante y su equipo de profesionales están dedicados a hacerte sentir renovada y radiante.');
